### PR TITLE
newTrip.js created

### PR DESCRIPTION
**Pull request by fabbrob**

### CODE REVIEW

**Comment by fabbrob** [comment]
still need to add the styling (it's done) but dont want to create any merge conflicts

**Comment by fabbrob** [comment]
also need to set up the modules and test it works but will get that sorted once my local gets up to date

**Comment by Whishes** [comment]
> still need to add the styling (it's done) but dont want to create any merge conflicts

The last line in the main branch's css is 314 so you can always press enter until you get down to that line # and at least the conflicts involving that stuff should be solved

**Comment by Whishes** [comment]
> also need to set up the modules and test it works but will get that sorted once my local gets up to date

with this, it might just be worth making a clone of the main branch and merging into that with all your code :) should be able to test with the updated main and not need to rush to pump out the changes so main isn't broken. 

There's also no branch protections on any branch besides main so you can do however many PRs you want and handle them however you want

**Review by elisabethmj — APPROVED** [review]

**Review by Whishes — APPROVED** [review]

**Pull request merged**
